
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./articles:/app/articles
      - ./settings.json:/app/settings.json

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
